# Generated by Django 4.2 on 2024-10-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0002_alter_sale_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="price",
            field=models.FloatField(),
        ),
    ]
